Script started on Mon 03 Jan 2022 11:43:26 PM PST
]0;jiancoz@zuma:Assignment1[jiancoz@zuma Assignment1]$ gcc weekday.c -o weekday
]0;jiancoz@zuma:Assignment1[jiancoz@zuma Assignment1]$ ./weekday
Please enter a canlender date:
Day, d = 12  12
Month, m = 1
Year, y = 2002  22
For the calender date 1/12/2022, the day of the week is 4.
This is a Wednesday
]0;jiancoz@zuma:Assignment1[jiancoz@zuma Assignment1]$ ./weekday
Please enter a canlender date:
Day, d = 1
Month, m = 1
Year, y = 2023
For the calender date 1/1/2023, the day of the week is 1.
This is a Sunday
]0;jiancoz@zuma:Assignment1[jiancoz@zuma Assignment1]$ ./weekday
Please enter a canlender date:
Day, d = 4
Month, m = 10
Year, y = 1965
For the calender date 10/4/1965, the day of the week is 2.
This is a Monday
]0;jiancoz@zuma:Assignment1[jiancoz@zuma Assignment1]$ exit
exit

Script done on Mon 03 Jan 2022 11:45:03 PM PST
