Script started on Mon 17 Jan 2022 06:43:46 PM PST
]0;jiancoz@zuma:hw2[jiancoz@zuma hw2]$ ./Phto[K[K[KhotoLab
------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
Please make your choice:11
EngPlaza.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

EngPlaza.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

EngPlaza.ppm was read successfully!
colorfilter.ppm was saved successfully. 
colorfilter.jpg was stored for viewing. 
Color Filter tested!

EngPlaza.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge tested!

EngPlaza.ppm was read successfully!
shuffle.ppm was saved successfully. 
shuffle.jpg was stored for viewing. 
Shuffle tested!

EngPlaza.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
VFlip tested!

EngPlaza.ppm was read successfully!
vmirror.ppm was saved successfully. 
vmirror.jpg was stored for viewing. 
VMirror tested!

EngPlaza.ppm was read successfully!
'Border' operation is done!
border.ppm was saved successfully. 
border.jpg was stored for viewing. 
AddBorder tested!

------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
Please make your choice:12
]0;jiancoz@zuma:hw2[jiancoz@zuma hw2]$ exit
exit

Script done on Mon 17 Jan 2022 06:44:12 PM PST
