Script started on Wed 02 Feb 2022 09:55:58 PM PST
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ make clean
rm -f *.o
rm -f PhotoLab
rm -f PhotoLabTest
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ make
gcc -c -Wall -ansi -std=c99 PhotoLab.c -o PhotoLab.o
gcc -c -Wall -ansi -std=c99 FileIO.c -o FileIO.o
gcc -c -Wall -ansi -std=c99 DIPs.c -o DIPs.o
gcc -c -Wall -ansi -std=c99 Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -lm -Wall -ansi -std=c99 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab
gcc -c -DDEBUG -Wall -ansi -std=c99 PhotoLab.c -o PhotoLabTest.o
gcc -lm -Wall -ansi -std=c99 PhotoLabTest.o FileIO.o -L. -lfilter -o PhotoLabTest
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
Please make your choice: 15
EngPlaza.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
EngPlaza.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
EngPlaza.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
EngPlaza.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
EngPlaza.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
EngPlaza.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
EngPlaza.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
EngPlaza.ppm was read.
border.ppm was saved. 
border.jpg was stored.
EngPlaza.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
EngPlaza.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
EngPlaza.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
EngPlaza.ppm was read.
blur.ppm was saved. 
blur.jpg was stored.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
Please make your choice: 16
You exit the program.
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ make PhotoLabTest
make: `PhotoLabTest' is up to date.
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ ./PhotoLabTest
EngPlaza.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
Black & White tested!

EngPlaza.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

EngPlaza.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

EngPlaza.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
Edge Detection tested!

EngPlaza.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
VMirror tested!

EngPlaza.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
VFlip tested!

EngPlaza.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle tested!

EngPlaza.ppm was read.
border.ppm was saved. 
border.jpg was stored.
Border tested!

EngPlaza.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
Noise tested!

EngPlaza.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
Sharpen tested!

EngPlaza.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
Posterize tested!

EngPlaza.ppm was read.
blur.ppm was saved. 
blur.jpg was stored.
Motion Blur tested!

]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ touch Advanced.c
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ make PhotoLab
gcc -c -Wall -ansi -std=c99 Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -lm -Wall -ansi -std=c99 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab
]0;jiancoz@zuma:hw3[jiancoz@zuma hw3]$ exit
exit

Script done on Wed 02 Feb 2022 09:56:54 PM PST
